var questions = Array(
/*1*/    {question: "Which of the following statements about the Spark driver is incorrect?", 
        A: " The Spark driver is the node in which the Spark application's main method runs to coordinate the Spark application",
        B:" The Spark driver is horizontally scaled to increase overall processing throughput.",
        C:" The Spark driver contains the SparkContext object.",
        D:" The Spark driver is responsible for scheduling the execution of data by various worker nodes in cluster mode.",
        E:" The Spark driver should be as close as possible to worker nodes for optimal performance.",
        correct:"B",
    },

/*2*/    {question:"Which of the following describes nodes in cluster-mode Spark?",
        A:" Nodes are the most granular level of execution in the Spark execution hierarchy.",
        B:" There is only one node and it hosts both the driver and executors.",
        C:" Nodes are another term for executors, so they are processing engine instances for performing computations.",
        D:" There are driver nodes and worker nodes, both of which can scale horizontally.",
        E:" Worker nodes are machines that host the executors responsible for the execution of tasks.",
        correct:"E",
    },

/*3*/    {question:"Which of the following statements about slots is true?",
        A:" There must be more slots than executors.",
        B:" There must be more tasks than slots.",
        C:" Slots are the most granular level of execution in the Spark execution hierarchy.",
        D:" Slots are not used in cluster mode.",
        E:" Slots are resources for parallelization within a Spark application.",
        correct:"E",
    },

/*4*/    {question:"Which of the following is a combination of a block of data and a set of transformers that will run on a single executor?",
        A:" Executor",
        B:" Node",
        C:" Job",
        D:" Task",
        E:" Slot",
        correct:"D",
    },

/*5*/    {question:"Which of the following is a group of tasks that can be executed in parallel to compute the same set of operations on potentially multiple machines?",
        A:" Job",
        B:" Slot",
        C:" Executor",
        D:" Task",
        E:" Stage",
        correct:"E",
    },
    
/*6*/    {question:"Which of the following describes a shuffle?",
        A:" A shuffle is the process by which data is compared across partitions.",
        B:" A shuffle is the process by which data is compared across executors.",
        C:" A shuffle is the process by which partitions are allocated to tasks.",
        D:" A shuffle is the process by which partitions are ordered for write.",
        E:" A shuffle is the process by which tasks are ordered for execution.",
        correct:"A",
    },
    
/*7*/    {question:"DataFrame df is very large with a large number of partitions, more than there are executors in the cluster. Based on this situation, which of the following is incorrect? Assume there is one core per executor.",
        A:" Performance will be suboptimal because not all executors will be utilized at the same time.",
        B:" Performance will be suboptimal because not all data can be processed at the same time.",
        C:" There will be a large number of shuffle connections performed on DataFrame df when operations inducing a shuffle are called.",
        D:" There will be a lot of overhead associated with managing resources for data processing within each task.",
        E:" There might be risk of out-of-memory errors depending on the size of the executors in the cluster.",
        correct:"A",
    },
    
/*8*/    {question:"Which of the following operations will trigger evaluation?",
        A:" DataFrame.filter()",
        B:" DataFrame.distinct()",
        C:" DataFrame.intersect()",
        D:" DataFrame.join()",
        E:" DataFrame.count()",
        correct:"E",
    },
    
/*9*/    {question:"Which of the following describes the difference between transformations and actions?",
        A:" Transformations work on DataFrames/Datasets while actions are reserved for native language objects",
        B:" There is no difference between actions and transformations.",
        C:" Actions are business logic operations that do not induce execution while transformations are execution triggers focused on returning results",
        D:" Actions work on DataFrames/Datasets while transformations are reserved for native language objects",
        E:" Transformations are business logic operations that do not induce execution while actions are execution triggers focused on returning results.",
        correct:"E",
    },
    
/*10*/    {question:"Which of the following DataFrame operations is always classified as a narrow transformation?",
        A:" DataFrame.sort()",
        B:" DataFrame.distinct()",
        C:" DataFrame.repartition()",
        D:" DataFrame.select()",
        E:" DataFrame.join()",
        correct:"D",
    },
    
/*11*/    {question:"Spark has a few different execution/deployment modes: cluster, client, and local. Which of the following describes Spark's execution/deployment mode?",
        A:" Spark's execution/deployment mode determines where the driver and executors are physically located when a Spark application is run",
        B:" Spark's execution/deployment mode determines which tasks are allocated to which executors in a cluster",
        C:" Spark's execution/deployment mode determines which node in a cluster of nodes is responsible for running the driver program",
        D:" Spark's execution/deployment mode determines exactly how many nodes the driver will connect to when a Spark application is run",
        E:" Spark's execution/deployment mode determines whether results are run interactively in a notebook environment or in batch",
        correct:"A",
    },
    
/*12*/    {question:"Which of the following cluster configurations will ensure the completion of a Spark application in light of a worker node failure?",
        A:" Scenario #1",
        B:" They should all ensure completion because worker nodes are fault-tolerant.",
        C:" Scenario #4",
        D:" Scenario #5",
        E:" Scenario #6",
        correct:"B",
        image: "images/12.png",
        extra:"Note: each configuration has roughly the same compute power using 100GB of RAM and 200 cores."
    },
    
/*13*/    {question:"Which of the following describes out-of-memory errors in Spark?",
        A:"An out-of-memory error occurs when either the driver or an executor does not have enough memory to collect or process the data allocated to it.",
        B:"An out-of-memory error occurs when Spark's storage level is too lenient and allows data objects to be cached to both memory and disk.",
        C:"An out-of-memory error occurs when there are more tasks than are executors regardless of the number of worker nodes.",
        D:"An out-of-memory error occurs when the Spark application calls too many transformations in a row without calling an action regardless of the size of the data object on which the transformations are operating",
        E:"An out-of-memory error occurs when too much data is allocated to the driver for computational purposes.",
        correct:"A",
    },
    
/*14*/    {question:"Which of the following is the default storage level for persist() for a non-streaming DataFrame/Dataset?",
        A:"MEMORY_AND_DISK",
        B:"MEMORY_AND_DISK_SER",
        C:"DISK_ONLY",
        D:"MEMORY_ONLY_SER",
        E:"MEMORY_ONLY",
        correct:"A",
    },
    
/*15*/    {question:"Which of the following describes a broadcast variable?",
        A:"A broadcast variable is a Spark object that needs to be partitioned onto multiple worker nodes because it's too large to fit on a single worker node.",
        B:"A broadcast variable can only be created by an explicit call to the broadcast() operation.",
        C:"A broadcast variable is entirely cached on the driver node so it doesn't need to be present on any worker nodes.",
        D:" A broadcast variable is entirely cached on each worker node so it doesn't need to be shipped or shuffled between nodes with each stage.",
        E:"A broadcast variable is saved to the disk of each worker node to be easily read into memory when needed.",
        correct:"D",
    },
    
/*16*/    {question:"Which of the following operations is most likely to induce a skew in the size of your data's partitions?",
        A:"DataFrame.collect()",
        B:"DataFrame.cache()",
        C:"DataFrame.repartition(n)",
        D:"DataFrame.coalesce(n)",
        E:"DataFrame.persist()",
        correct:"D",
    },
    
/*17*/    {question:"Which of the following data structures are Spark DataFrames built on top of?",
        A:"Arrays",
        B:"Strings",
        C:"RDDs",
        D:"Vectors",
        E:"SQL Tables",
        correct:"C",
    },
    
/*18*/    {question:"Which of the following code blocks returns a DataFrame containing only column storeId and column division from DataFrame storesDF?",
        A:'storesDF.select("storeId").select("division")',
        B:'storesDF.select(storeId, division)',
        C:'storesDF.select("storeId", "division")',
        D:'storesDF.select(col("storeId", "division"))',
        E:' storesDF.select(storeId).select(division)',
        correct:"C",
    },
    
/*19*/    {question:"Which of the following code blocks returns a DataFrame containing all columns from DataFrame storesDF except for column sqft and column customerSatisfaction? </br> A sample of DataFrame storesDF is below:",
        A:'storesDF.drop("sqft", "customerSatisfaction")',
        B:'storesDF.select("storeId", "open", "openDate", "division")',
        C:'storesDF.select(-col(sqft), -col(customerSatisfaction))',
        D:'storesDF.drop(sqft, customerSatisfaction)',
        E:'storesDF.drop(col(sqft), col(customerSatisfaction))',
        correct:"A",
        image: "images/19.png"
    },
    
/*20*/    {question:'The below code shown block contains an error. The code block is intended to return a DataFrame containing only the rows from DataFrame storesDF where the value in DataFrame storesDF'+"s"+ '"sqft" column is less than or equal to 25,000. Assume DataFrame storesDF is the only defined language variable. Identify the error.</br> Code block:</br> storesDF.filter(sqft <= 25000)',
        A:'The column name sqft needs to be quoted like storesDF.filter("sqft" <=25000).',
        B:'The column name sqft needs to be quoted and wrapped in the col() function like storesDF.filter(col("sqft") <= 25000).',
        C:'The sign in the logical condition inside filter() needs to be changed from <= to >.',
        D:'The sign in the logical condition inside filter() needs to be changed from <= to >=.',
        E:'The column name sqft needs to be wrapped in the col() function like storesDF.filter(col(sqft) <= 25000).',
        correct:"B",
    },
    
/*21*/    {question:"The code block shown below should return a DataFrame containing only the rows from DataFrame storesDF where the value in column sqft is less than or equal to 25,000 OR the value in column customerSatisfaction is greater than or equal to 30. Choose the response that correctly fills in the numbered blanks within the code block to complete this task.</br> Code block:</br> storesDF.__1__(__2__ __3__ __4__)",
        A:'<ol><li>filter</li><li> (col("sqft") <= 25000)</li><li>|</li><li>(col("customerSatisfaction") >= 30)</li></ol>',
        B:'<ol><li>drop</li><li>(col(sqft) <= 25000)</li><li>|</li><li>(col(customerSatisfaction) >= 30)</li></ol>',
        C:'<ol><li>filter</li><li>col("sqft") <= 25000</li><li>|</li><li>col("customerSatisfaction") >= 30</li></ol>',
        D:'<ol><li>filter</li><li>col("sqft") <= 25000</li><li>or</li><li>col("customerSatisfaction") >= 30</li></ol>',
        E:'<ol><li>filter</li><li>(col("sqft") <= 25000)</li><li>or</li><li>(col("customerSatisfaction") >= 30)</li></ol>',
        correct:"A",
    },
    
/*22*/    {question:"Which of the following operations can be used to convert a DataFrame column from one type to another type?",
        A:"col().cast()",
        B:"convert()",
        C:"castAs()",
        D:"col().coerce()",
        E:"col()",
        correct:"A",
    },
    
/*23*/    {question:"Which of the following code blocks returns a new DataFrame with a new column sqft100 that is 1/100th of column sqft in DataFrame storesDF? Note that column sqft100 is not in the original DataFrame storesDF.",
        A:'storesDF.withColumn("sqft100", col("sqft") * 100)',
        B:'storesDF.withColumn("sqft100", sqft / 100)',
        C:' storesDF.withColumn(col("sqft100"), col("sqft") / 100)',
        D:'storesDF.withColumn("sqft100", col("sqft") / 100)',
        E:'storesDF.newColumn("sqft100", sqft / 100)',
        correct:"D",
    },
    
/*24*/    {question:"Which of the following code blocks returns a new DataFrame from DataFrame storesDF where column numberOfManagers is the constant integer 1?",
        A:'storesDF.withColumn("numberOfManagers", col(1))',
        B:'storesDF.withColumn("numberOfManagers", 1)',
        C:'storesDF.withColumn("numberOfManagers", lit(1))',
        D:'storesDF.withColumn("numberOfManagers", lit("1"))',
        E:'storesDF.withColumn("numberOfManagers", IntegerType(1))',
        correct:"C",
    },
    
/*25*/    {question:"The code block shown below contains an error. The code block intends to return a new DataFrame where column storeCategory from DataFrame storesDF is split at the underscore character into column storeValueCategory and column storeSizeCategory. Identify the error.<br/> A sample of DataFrame storesDF is displayed below:",
        A:"The split() operation comes from the imported functions object. It accepts a string column name and split character as arguments. It is not a method of a Column object.",
        B:"The split() operation comes from the imported functions object. It accepts a Column object and split character as arguments. It is not a method of a Column object.",
        C:"The index values of 0 and 1 should be provided as second arguments to the split() operation rather than indexing the result.",
        D:"The index values of 0 and 1 are not correct — they should be 1 and 2, respectively",
        E:"The withColumn() operation cannot be called twice in a row.",
        correct:"B",
        image: "images/25.png",
        extra: 'Code block:<br/>(storesDF.withColumn(<br/>      "storeValueCategory", col("storeCategory").split("_")[0]<br/>).withColumn(<br/>"storeSizeCategory", col("storeCategory").split("_")[1]<br/>)<br/>)'
    },
    
/*26*/    {question:"Which of the following operations can be used to split an array column into an individual DataFrame row for each element in the array?",
        A:"extract()",
        B:"split()",
        C:"explode()",
        D:" arrays_zip()",
        E:"unpack()",
        correct:"C",
    },
    
/*27*/    {question:"Which of the following code blocks returns a new DataFrame where column storeCategory is an all-lowercase version of column storeCategory in DataFrame storesDF? Assume DataFrame storesDF is the only defined language variable.",
        A:'storesDF.withColumn("storeCategory",lower(col("storeCategory")))',
        B:'storesDF.withColumn("storeCategory",col("storeCategory").lower())',
        C:'storesDF.withColumn("storeCategory",tolower(col("storeCategory")))',
        D:'storesDF.withColumn("storeCategory", lower("storeCategory"))',
        E:'storesDF.withColumn("storeCategory", lower(storeCategory))',
        correct:"A",
    },
    
/*28*/    {question:'The code block shown below contains an error. The code block is intended to return a new DataFrame where column division from DataFrame storesDF has been renamed to column state and column managerName from DataFrame storesDF has been renamed to column managerFullName. Identify the error.<br/>Code block:<br/>(storesDF.withColumnRenamed("state", "division")<br/>.withColumnRenamed("managerFullName", "managerName"))',
        A:'Both arguments to operation withColumnRenamed() should be wrapped in the col() operation',
        B:'The operations withColumnRenamed() should not be called twice, and the first argument should be ["state", "division"] and the second argument should be ["managerFullName", "managerName"].',
        C:'The old columns need to be explicitly dropped.',
        D:'The first argument to operation withColumnRenamed() should be the old column name and the second argument should be the new column name',
        E:'The operation withColumnRenamed() should be replaced with withColumn().',
        correct:"D",
    },
    
/*29*/    {question:"Which of the following code blocks returns a DataFrame where rows in DataFrame storesDF containing missing values in every column have been dropped?",
        A:'storesDF.nadrop("all")',
        B:'storesDF.na.drop("all", subset = "sqft")',
        C:'storesDF.dropna()',
        D:'storesDF.na.drop()',
        E:'storesDF.na.drop("all")',
        correct:"E",
    },
    
/*30*/    {question:"Which of the following operations fails to return a DataFrame where every row is unique?",
        A:"DataFrame.distinct()",
        B:"DataFrame.drop_duplicates(subset = None)",
        C:"DataFrame.drop_duplicates()",
        D:"DataFrame.dropDuplicates()",
        E:'DataFrame.drop_duplicates(subset = "all")',
        correct:"E",
    },
    
/*31*/    {question:"Which of the following code blocks will not always return the exact number of distinct values in column division?",
        A:'storesDF.agg(approx_count_distinct(col("division")).alias("divisionDistinct"))',
        B:'storesDF.agg(approx_count_distinct(col("division"),0).alias("divisionDistinct"))',
        C:'storesDF.agg(countDistinct(col("division")).alias("divisionDistinct"))',
        D:'storesDF.select("division").dropDuplicates().count()',
        E:'storesDF.select("division").distinct().count()',
        correct:"A",
    },
    
/*32*/    {question:'The code block shown below should return a new DataFrame with the mean of column sqft from DataFrame storesDF in column sqftMean. Choose the response that correctly fills in the numbered blanks within the code block to complete this task.<br/>Code block:<br/>storesDF.__1__(__2__(__3__).alias("sqftMean"))',
        A:'<ol><li>agg</li><li>mean</li><li>col("sqft")</li></ol>',
        B:'<ol><li>mean</li><li>col</li><li>"sqft"</li></ol>',
        C:'<ol><li>withColumn</li><li>mean</li><li>col("sqft")</li></ol>',
        D:'<ol><li>agg</li><li>mean</li><li>"sqft"</li></ol>',
        E:'<ol><li>agg</li><li>average</li><li>col("sqft")</li></ol>',
        correct:"A",
    },
    
/*33*/    {question:"Which of the following code blocks returns the number of rows in DataFrame storesDF?",
        A:' storesDF.withColumn("numberOfRows", count())',
        B:'storesDF.withColumn(count().alias("numberOfRows"))',
        C:"storesDF.countDistinct()",
        D:"storesDF.count()",
        E:"storesDF.agg(count())",
        correct:"D",
    },
    
/*34*/    {question:"Which of the following code blocks returns the sum of the values in column sqft in DataFrame storesDF grouped by distinct value in column division?",
        A:'storesDF.groupBy.agg(sum(col("sqft")))',
        B:'storesDF.groupBy("division").agg(sum())',
        C:'storesDF.agg(groupBy("division").sum(col("sqft")))',
        D:'storesDF.groupby.agg(sum(col("sqft")))',
        E:'storesDF.groupBy("division").agg(sum(col("sqft")))',
        correct:"E",
    },
    
/*35*/    {question:"Which of the following code blocks returns a DataFrame containing summary statistics only for column sqft in DataFrame storesDF?",
        A:'storesDF.summary("mean")',
        B:'storesDF.describe("sqft")',
        C:'storesDF.summary(col("sqft"))',
        D:'storesDF.describeColumn("sqft")',
        E:'storesDF.summary()',
        correct:"B",
    },
    
/*36*/    {question:"Which of the following operations can be used to sort the rows of a DataFrame?",
        A:"sort() and orderBy()",
        B:"orderby()",
        C:"sort() and orderby()",
        D:" orderBy()",
        E:"sort()",
        correct:"A",
    },
    
/*37*/    {question:"The code block shown below contains an error. The code block is intended to return a 15 percent sample of rows from DataFrame storesDF without replacement. Identify the error.<br/>Code block:<br/>storesDF.sample(True, fraction = 0.15)",
        A:"There is no argument specified to the seed parameter.",
        B:"There is no argument specified to the withReplacement parameter.",
        C:"The sample() operation does not sample without replacement — sampleby() should be used instead.",
        D:"The sample() operation is not reproducible.",
        E:"The first argument True sets the sampling to be with replacement.",
        correct:"E",
    },
    
/*38*/    {question:"Which of the following operations can be used to return the top n rows from a DataFrame?",
        A:" DataFrame.n()",
        B:"DataFrame.take(n)",
        C:"DataFrame.head",
        D:"DataFrame.show(n)",
        E:"DataFrame.collect(n)",
        correct:"B",
    },
    
/*39*/    {question:"The code block shown below should extract the value for column sqft from the first row of DataFrame storesDF. Choose the response that correctly fills in the numbered blanks within the code block to complete this task.<br/>Code block:<br/>__1__.__2__.__3__",
        A:'<ol><li>1. storesDF</li><li>first</li><li>col("sqft")</li></ol>',
        B:'<ol><li>storesDF</li><li>first</li><li>sqft</li></ol>',
        C:'<ol><li>storesDF</li><li>first</li><li>["sqft"]</li></ol>',
        D:'<ol><li>storesDF</li><li>first()</li><li>sqft</li></ol>',
        E:'<ol><li>storesDF</li><li>first()</li><li>col("sqft")</li></ol>',
        correct:"D",
    },
    
/*40*/    {question:"Which of the following lines of code prints the schema of a DataFrame?",
        A:"print(storesDF)",
        B:"storesDF.schema",
        C:"print(storesDF.schema())",
        D:"DataFrame.printSchema()",
        E:"DataFrame.schema()",
        correct:"D",
    },
    
/*41*/    {question:'In what order should the below lines of code be run in order to create and register a SQL UDF named "ASSESS_PERFORMANCE" using the Python function assessPerformance and apply it to column customerSatistfaction in table stores?<br/>Lines of code:<ol><li>spark.udf.register("ASSESS_PERFORMANCE", assessPerformance)</li><li>spark.sql("SELECT customerSatisfaction,assessPerformance(customerSatisfaction) AS result FROM stores")</li><li>spark.udf.register(assessPerformance, "ASSESS_PERFORMANCE")</li><li>spark.sql("SELECT customerSatisfaction,ASSESS_PERFORMANCE(customerSatisfaction) AS result FROM stores")</li></ol>',
        A:"3, 4",
        B:"1, 4",
        C:"3, 2",
        D:"2",
        E:"1, 2",
        correct:"B",
    },
    
/*42*/    {question:'In what order should the below lines of code be run in order to create a Python UDF assessPerformanceUDF() using the integer-returning Python function assessPerformance and apply it to column customerSatisfaction in DataFrame storesDF?<br/>Lines of code:<br/><ol><li>assessPerformanceUDF = udf(assessPerformance, IntegerType)</li><li>assessPerformanceUDF = spark.register.udf("ASSESS_PERFORMANCE",assessPerformance)</li><li>assessPerformanceUDF = udf(assessPerformance, IntegerType())</li><li>storesDF.withColumn("result",assessPerformanceUDF(col("customerSatisfaction")))</li><li>storesDF.withColumn("result",assessPerformance(col("customerSatisfaction")))</li><li>storesDF.withColumn("result",ASSESS_PERFORMANCE(col("customerSatisfaction")))</li></ol>',
        A:"3, 4",
        B:"2, 6",
        C:"3, 5",
        D:"1, 4",
        E:"2, 5",
        correct:"A",
    },
    
/*43*/    {question:"Which of the following operations can execute a SQL query on a table?",
        A:"spark.query()",
        B:"DataFrame.sql()",
        C:"spark.sql()",
        D:"DataFrame.createOrReplaceTempView()",
        E:"DataFrame.createTempView()",
        correct:"C",
    },
    
/*44*/    {question:"Which of the following code blocks creates a single-column DataFrame from Python list years which is made up of integers?",
        A:"spark.createDataFrame([years], IntegerType())",
        B:"spark.createDataFrame(years, IntegerType())",
        C:"spark.DataFrame(years, IntegerType())",
        D:"spark.createDataFrame(years)",
        E:"spark.createDataFrame(years, IntegerType)",
        correct:"B",
    },
    
/*45*/    {question:"Which of the following operations can be used to cache a DataFrame only in Spark’s memory assuming the default arguments can be updated?",
        A:"DataFrame.clearCache()",
        B:"DataFrame.storageLevel",
        C:"StorageLevel",
        D:"DataFrame.persist()",
        E:"DataFrame.cache()",
        correct:"D",
    },
    
/*46*/    {question:"The code block shown below contains an error. The code block is intended to return a new 4-partition DataFrame from the 8-partition DataFrame storesDF without inducing a shuffle. Identify the error.<br/>Code block:<br/>storesDF.repartition(4)",
        A:"The repartition operation will only work if the DataFrame has been cached to memory",
        B:"The repartition operation requires a column on which to partition rather than a number of partitions",
        C:"The number of resulting partitions, 4, is not achievable for an 8-partition DataFrame.",
        D:"The repartition operation induced a full shuffle. The coalesce operation should be used instead.",
        E:"The repartition operation cannot guarantee the number of result partitions.",
        correct:"D",
    },
    
/*47*/    {question:"Which of the following code blocks will always return a new 12-partition DataFrame from the 8-partition DataFrame storesDF?",
        A:"storesDF.coalesce(12)",
        B:"storesDF.repartition()",
        C:"storesDF.repartition(12)",
        D:"storesDF.coalesce()",
        E:'storesDF.coalesce(12, "storeId")',
        correct:"C",
    },
    
/*48*/    {question:"Which of the following Spark config properties represents the number of partitions used in wide transformations like join()?",
        A:"spark.sql.shuffle.partitions",
        B:"spark.shuffle.partitions",
        C:"spark.shuffle.io.maxRetries",
        D:"spark.shuffle.file.buffer",
        E:"spark.default.parallelism",
        correct:"A",
    },
    
/*49*/    {question:'In what order should the below lines of code be run in order to return a DataFrame containing a column openDateString, a string representation of Java’s SimpleDateFormat?<br/>Note that column openDate is of type integer and represents a date in the UNIX epoch format — the number of seconds since midnight on January 1st, 1970.<br/>An example of Java'+"'s"+' SimpleDateFormat is "Sunday, Dec 4, 2008 1:05 PM".<br/>A sample of storesDF is displayed below:',
        A:"2, 3",
        B:"2, 1",
        C:"6, 5",
        D:"2, 4",
        E:"6, 1",
        correct:"B",
        image: "images/49.png",
        extra:'Lines of code:<ol><li>storesDF.withColumn("openDateString",from_unixtime(col("openDate"), simpleDateFormat))</li><li>simpleDateFormat = "EEEE, MMM d, yyyy h:mm a"</li><li>storesDF.withColumn("openDateString",from_unixtime(col("openDate"), SimpleDateFormat()))</li><li>storesDF.withColumn("openDateString",date_format(col("openDate"), simpleDateFormat))</li><li>storesDF.withColumn("openDateString",date_format(col("openDate"), SimpleDateFormat()))</li><li>simpleDateFormat = "wd, MMM d, yyyy h:mm a"</li></ol>'
    },
    
/*50*/    {question:"Which of the following code blocks returns a DataFrame containing a column month, an integer representation of the month from column openDate from DataFrame storesDF?<br/>Note that column openDate is of type integer and represents a date in the UNIX epoch format — the number of seconds since midnight on January 1st, 1970.<br/>A sample of storesDF is displayed below:",
        A:'storesDF.withColumn("month", getMonth(col("openDate")))',
        B:'storesDF.withColumn("openTimestamp",col("openDate").cast("Timestamp")).withColumn("month", month(col("openTimestamp")))',
        C:'storesDF.withColumn("openDateFormat",col("openDate").cast("Date")).withColumn("month", month(col("openDateFormat")))',
        D:'storesDF.withColumn("month", substr(col("openDate"), 4, 2))',
        E:'storesDF.withColumn("month", month(col("openDate")))',
        correct:"B",
        image:"images/50.png"
    },
    
/*51*/    {question:"Which of the following operations performs an inner join on two DataFrames?",
        A:"DataFrame.innerJoin()",
        B:"DataFrame.join()",
        C:"Standalone join() function",
        D:"DataFrame.merge()",
        E:"DataFrame.crossJoin()",
        correct:"B",
    },
    
/*52*/    {question:"Which of the following code blocks returns a new DataFrame that is the result of an outer join between DataFrame storesDF and DataFrame employeesDF on column storeId?",
        A:'storesDF.join(employeesDF, "storeId", "outer")',
        B:'storesDF.join(employeesDF, "storeId")',
        C:'storesDF.join(employeesDF, "outer", col("storeId"))',
        D:'storesDF.join(employeesDF, "outer", storesDF.storeId == employeesDF.storeId)',
        E:'storesDF.merge(employeesDF, "outer", col("storeId"))',
        correct:"A",
    },
    
/*53*/    {question:'The below code block contains an error. The code block is intended to return a new DataFrame that is the result of an inner join between DataFrame storesDF and DataFrame employeesDF on column storeId and column employeeId which are in both DataFrames. Identify the error.<br/>Code block:<br/>storesDF.join(employeesDF, [col("storeId"), col("employeeId")])',
        A:'The join() operation is a standalone function rather than a method of DataFrame — the join() operation should be called where its first two arguments are storesDF and employeesDF.',
        B:'There must be a third argument to join() because the default to the how parameter is not "inner".',
        C:'The col("storeId") and col("employeeId") arguments should not be separate elements of a list — they should be tested to see if they'+"'re"+' equal to one another like col("storeId") == col("employeeId").',
        D:'There is no DataFrame.join() operation — DataFrame.merge() should be used instead.',
        E:'The references to "storeId" and "employeeId" should not be inside the col() function — removing the col() function should result in a successful join.',
        correct:"E",
    },
    
/*54*/    {question:"Which of the following Spark properties is used to configure the broadcasting of a DataFrame without the use of the broadcast() operation?",
        A:"spark.sql.autoBroadcastJoinThreshold",
        B:"spark.sql.broadcastTimeout",
        C:"spark.broadcast.blockSize",
        D:"spark.broadcast.compress",
        E:"spark.executor.memoryOverhead",
        correct:"A",
    },
    
/*55*/    {question:"The code block shown below should return a new DataFrame that is the result of a cross join between DataFrame storesDF and DataFrame employeesDF. Choose the response that correctly fills in the numbered blanks within the code block to complete this task.<br/>Code block:<br/>__1__.__2__(__3__)",
        A:'<ol><li>storesDF</li><li>crossJoin</li><li>employeesDF, "storeId"</li></ol>',
        B:'<ol><li>storesDF</li><li>join</li><li>employeesDF, "cross"</li></ol>',
        C:'<ol><li>storesDF</li><li>crossJoin</li><li>employeesDF, "storeId"</li></ol>',
        D:'<ol><li>storesDF</li><li>join</li><li>employeesDF, "storeId", "cross"</li></ol>',
        E:'<ol><li>storesDF</li><li>crossJoin</li><li>employeesDF</li></ol>',
        correct:"E",
    },
    
/*56*/    {question:"Which of the following operations performs a position-wise union on two DataFrames?",
        A:"The standalone concat() function",
        B:"The standalone unionAll() function",
        C:"The standalone union() function",
        D:"DataFrame.unionByName()",
        E:"DataFrame.union()",
        correct:"E",
    },
    
/*57*/    {question:"Which of the following code blocks writes DataFrame storesDF to file path filePath as parquet?",
        A:'storesDF.write.option("parquet").path(filePath)',
        B:"storesDF.write.path(filePath)",
        C:"storesDF.write().parquet(filePath)",
        D:"storesDF.write(filePath)",
        E:"storesDF.write.parquet(filePath)",
        correct:"E",
    },
    
/*58*/    {question:'The code block shown below contains an error. The code block is intended to write DataFrame storesDF to file path filePath as parquet and partition by values in column division. Identify the error<br/>Code block:<br/>storesDF.write.repartition("division").parquet(filePath)',
        A:" The argument division to operation repartition() should be wrapped in the col() function to return a Column object.",
        B:"There is no parquet() operation for DataFrameWriter — the save() operation should be used instead.",
        C:"There is no repartition() operation for DataFrameWriter — the partitionBy() operation should be used instead.",
        D:"DataFrame.write is an operation — it should be followed by parentheses to return a DataFrameWriter.",
        E:"The mode() operation must be called to specify that this write should not overwrite existing files.",
        correct:"C",
    },
    
/*59*/    {question:"Which of the following code blocks reads a parquet at the file path filePath into a DataFrame?",
        A:"spark.read().parquet(filePath)",
        B:'spark.read().path(filePath, source = "parquet")',
        C:'spark.read.path(filePath, source = "parquet")',
        D:"spark.read.parquet(filePath)",
        E:"spark.read().path(filePath)",
        correct:"D",
    },
    
/*60*/    {question:"Which of the following code blocks reads JSON at the file path filePath into a DataFrame with the specified schema schema?",
        A:'spark.read().schema(schema).format(json).load(filePath)',
        B:'spark.read().schema(schema).format("json").load(filePath)',
        C:'spark.read.schema("schema").format("json").load(filePath)',
        D:'spark.read.schema("schema").format("json").load(filePath)',
        E:'spark.read.schema(schema).format("json").load(filePath)',
        correct:"E",
    }

)
